### ISSUE TITLE
Scroll Position Preserved when unintentional

### ISSUE THREAD

**Issue by bergermaestro** [dylanfaelker/PersonalWebsite#21]
When Navigating to both the Infinity Chess and Stock Portfolio pages, scroll position is preserved so you are not at the top of the page. 

Although to be fair this will probably be fixed when you switch to next.js

![coding gif](https://i.giphy.com/media/scZPhLqaVOM1qG4lT9/giphy.webp)
![coding gif](https://i.giphy.com/media/bi6RQ5x3tqoSI/giphy.webp)

**Comment by dylanfaelker** [comment]
Fixed it without having to move to next.js
